const codebotDataModels = {
            programmingLanguages: ['Python', 'JavaScript', 'Java', 'C++', 'Lua', 'HTML', 'CSS', 'Ruby', 'Swift', 'Go', 'C#', 'PHP', 'TypeScript', 'Kotlin', 'Rust', 'YAML', 'MATLAB', 'Perl'],
            frameworks: ['Django', 'Flask', 'React', 'Vue', 'Angular', 'Spring Boot', 'Ruby on Rails', 'Laravel', 'Express', 'ASP.NET'],
            codeSnippets: {
                Python: ['print("Hello, World!")', 'for i in range(10): print(i)', 'import math'],
                JavaScript: ['console.log("Hello, World!");', 'for(let i = 0; i < 10; i++) { console.log(i); }', 'document.addEventListener("DOMContentLoaded", function() {});'],
                HTML: ['<!DOCTYPE html>', '<html>', '<body><h1>Hello, World!</h1></body>', '</html>'],
                CSS: ['body { font-family: Arial, sans-serif; }', 'h1 { color: blue; }'],
                Ruby: ['puts "Hello, World!"', '5.times { puts "Ruby loop" }'],
                Swift: ['import UIKit', 'print("Hello, World!")'],
                Go: ['package main', 'import "fmt"', 'func main() { fmt.Println("Hello, World!") }'],
                YAML: ['key: value', 'list:\n- item1\n- item2'],
                MATLAB: ['disp("Hello, World!")', 'for i = 1:10, disp(i), end'],
                Perl: ['print "Hello, World!\n";', 'for ($i = 0; $i < 10; $i++) { print "$i\n"; }'],
            },
            userQueries: [
                'How to print in Python?', 'Loop example in JavaScript', 'Basic HTML structure', 'Styling text in CSS', 'Loop in Ruby',
                'Importing libraries in Swift', 'Go Hello World', 'Java Hello World', 'C++ Hello World', 'C# Hello World', 'PHP Hello World',
                'TypeScript Hello World', 'Kotlin Hello World', 'Rust Hello World',
                'How to initialize a React component?', 'How to setup Django?', 'Vue directives guide', 'Spring Boot project setup', 'Ruby on Rails MVC structure',
            ],
            botResponses: [
                'To print in Python, you can use the print function like this: print("Your text here").',
                'In JavaScript, a basic for loop looks like this: for(let i = 0; i < 10; i++) { console.log(i); }',
                'The basic structure of an HTML document is as follows: <!DOCTYPE html><html><body><h1>Your content here</h1></body></html>',
                'To style text in CSS, you can use the color property like this: h1 { color: blue; }',
                'In Ruby, you can use the times method for a basic loop. For example: 5.times { puts "Ruby loop" }',
                'To initialize a React component, you would start by importing React and creating a class or functional component. For example: `class MyComponent extends React.Component { render() { return <div>Hello World</div>; } }`',
                'Setting up Django requires installing Django using pip, then using the `django-admin startproject` command.',
                'Vue directives are special tokens in the markup that tell Vue to do something. Examples include v-bind, v-model, and v-for.',
                'To setup a Spring Boot project, you can use the Spring Initializr website to generate a project template.',
                'Ruby on Rails follows the MVC (Model-View-Controller) pattern. The model represents the data, the view displays the data, and the controller mediates input, converting it to commands for the model or view.',
            ],
        };
